version: '3.7'
services:
    postgres:
        image: postgres:10.5
        restart: always
        environment: 
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=postgres_test
          - POSTGRES_HOST=postgres
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '6000:5432'
        expose:
          - 5432
        volumes:  
          # copy the sql script to create tables
          - ./DB-schema.sql:/docker-entrypoint-initdb.d/create_tables.sql

#https://levelup.gitconnected.com/creating-and-filling-a-postgres-db-with-docker-compose-e1607f6f882f
