name: deploy
on: push

jobs:
  # Label of the container job
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install server and frontend dependencies
        run: cd ./server && npm install && cd ../client && npm install
      - name: build client
        run: cd ./server && npm run buildprod
      - name: check if build exists pre deploy
        run: cd ./server && ls -la && heroku run bash && ls -la && exit
      - name: Deploy
        if: ${{ github.event_name == 'push' && !contains(toJson(github.event.commits.*.message), '#skip')}}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "thirtychat30"
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          appdir: "server"
          branch: "master"
      - name: check if build exists post deploy
        run: cd ./server && ls -la && heroku run bash && ls -la && exit
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(toJson(github.event.commits.*.message),'#skip')}}
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
